### ISSUE TITLE
install Extention

### ISSUE THREAD

**Issue by Mehran** [vstostap/chrome-pwd-spy#1]
Where can i Download and install extention ?

**Comment by vstostap** [comment]
you might download this repository and load it manually in your victim's chrome developers mode,
it installs immediately.
I thinks it's better one option than register it in chrome extensions store.
Also it has fake extension name and icon to prevent any suspicions (google drawings by default, you can set your own preferences in manifest.json).
and don't forget to set your elasticemail credentials in config file as described in readme.md
